# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TaxrefApi
                                 A QGIS plugin
 This plugin install a processing algorithm to download and join data from French TAXREF API, provided by the French National Museum of Natural History
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-10-09
        copyright            : (C) 2020 by Yann Voté
        email                : ygversil@lilo.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Yann Voté'
__date__ = '2020-10-09'
__copyright__ = '(C) 2020 by Yann Voté'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TaxrefApi class from file TaxrefApi.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .taxref_api import TaxrefApiPlugin
    return TaxrefApiPlugin()
